### ISSUE TITLE
Fix access for Scotland Folder

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/glasgow-class-6#69]
This folder is meant to be accessible to volunteers, but due to GDPR considerations folders were moved and permissions changed, so this has changed also. 

The folder is https://drive.google.com/drive/folders/0B_sRUD1YDjY-WlJDcFVBc2UtWGs?resourcekey=0-XDSzLLDQ55C-ZBRq-pJkLQ&usp=share_link

@emcglackenr1 and @caromelendezl to fix this. 

Relates to [#131](https://github.com/CodeYourFuture/Scotland-Planning/issues/131)

**Comment by SallyMcGrath** [comment]
I would make a group for each access level and add people to that group. https://www.techrepublic.com/article/how-to-easily-share-files-and-folders-with-groups-in-google-drive/

Then add the group to the file instead of individuals.

This is so you can remove all file access in one go if you need to.

If for some reason I don't know (likely!) you can't make groups, I sometimes make shared folders named by access type instead, and add people to the folder.

Adding people 1 by 1 to individual files is the problem, so organise some kind of group access that makes sense to your team.

Asking your Tech Ed team to define this structure is a good idea. Lay out the problem and ask them to set something up that solves it. Here's an example of me doing this with my volunteer team https://codeyourfuture.slack.com/archives/C012UUW69S8/p1672817896064909

**Comment by caromelendezl** [comment]
thank you @SallyMcGrath, @ClaireBickley mentioned we should not add individually, but the info on this folder is info that anyone should be able to see as it's not sensible (and we will not store sensible info either).

@ClaireBickley can't we just not leave this one as anyone can have access but only a few can edit info?

The folder is https://drive.google.com/drive/folders/0B_sRUD1YDjY-WlJDcFVBc2UtWGs?resourcekey=0-XDSzLLDQ55C-ZBRq-pJkLQ&usp=share_link

**Comment by ClaireBickley** [comment]
if there is no confidential info held then sure

There will come a point when volunteers need access to sensitive info (e.g. trainee tracker) at which point you'll need a folder on your sensitive drive and can give access in the way Sally has described

you can create a Google group to give access in this way but best not use it to email lots of people at once

**Comment by caromelendezl** [comment]
Thank you @ClaireBickley 
cc' @emcglackenr1

**Comment by emcglackenr1** [comment]
Hi there, it looks like I can't actually create a Google Group. So I have done it via folders instead.

**Comment by ClaireBickley** [comment]
I can create them, just let me know how many and what they should be called and I'll do it.
